name: Update flake

on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:

jobs:
  update:
    if: github.repository == 'amadejkastelic/nix-userstyles'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.PAT }}

      - uses: DeterminateSystems/nix-installer-action@main

      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "flake.lock: Update"
